import React, { useState } from 'react'
import { outletColor, outletInitials } from '../utils/helpers'

const OUTLET_DOMAINS = {
  // UK
  'BBC':                      'bbc.co.uk',
  'BBC News':                 'bbc.co.uk',
  'The Guardian':             'theguardian.com',
  'The Telegraph':            'telegraph.co.uk',
  'The Independent':          'independent.co.uk',
  'Sky News':                 'news.sky.com',
  'Daily Mail':               'dailymail.co.uk',
  'Financial Times':          'ft.com',
  'The Sun':                  'thesun.co.uk',
  'Metro':                    'metro.co.uk',
  'Evening Standard':         'standard.co.uk',
  'The Spectator':            'spectator.co.uk',
  'New Statesman':            'newstatesman.com',
  'The Times':                'thetimes.com',
  'The Mirror':               'mirror.co.uk',
  'iNews':                    'inews.co.uk',
  'Channel 4 News':           'channel4.com',
  'GB News':                  'gbnews.com',
  'Daily Express':            'express.co.uk',
  // US
  'Reuters':                  'reuters.com',
  'AP News':                  'apnews.com',
  'AP New':                   'apnews.com',
  'New York Times':           'nytimes.com',
  'Washington Post':          'washingtonpost.com',
  'Fox News':                 'foxnews.com',
  'CNN':                      'cnn.com',
  'NBC News':                 'nbcnews.com',
  'NPR':                      'npr.org',
  'The Hill':                 'thehill.com',
  'Politico':                 'politico.com',
  'Breitbart':                'breitbart.com',
  'Vox':                      'vox.com',
  'The Economist':            'economist.com',
  'The Atlantic':             'theatlantic.com',
  'Newsweek':                 'newsweek.com',
  'HuffPost':                 'huffpost.com',
  'National Review':          'nationalreview.com',
  'Time':                     'time.com',
  'USA Today':                'usatoday.com',
  'The Daily Beast':          'thedailybeast.com',
  'CTV News':                 'ctvnews.ca',
  'Middle East Eye':          'middleeasteye.net',
  'Wall Street Journal':      'wsj.com',
  'Bloomberg':                'bloomberg.com',
  'New York Post':            'nypost.com',
  'CBS News':                 'cbsnews.com',
  'ABC News':                 'abcnews.go.com',
  'Axios':                    'axios.com',
  'MSNBC':                    'msnbc.com',
  'Business Insider':         'businessinsider.com',
  'ProPublica':               'propublica.org',
  'Foreign Policy':           'foreignpolicy.com',
  'The New Yorker':           'newyorker.com',
  'The Daily Wire':           'dailywire.com',
  'Slate':                    'slate.com',
  'New York Magazine':        'nymag.com',
  'MarketWatch':              'marketwatch.com',
  'Voice of America':         'voanews.com',
  'LBC News':                 'lbc.co.uk',
  'The Hindu':                'thehindu.com',
  'Dawn':                     'dawn.com',
  // International — existing
  'Al Jazeera':               'aljazeera.com',
  'Deutsche Welle':           'dw.com',
  'France 24':                'france24.com',
  'ABC News Australia':       'abc.net.au',
  'CBC News':                 'cbc.ca',
  'South China Morning Post': 'scmp.com',
  'Times of India':           'timesofindia.com',
  // International — new
  'Euronews':                 'euronews.com',
  'Le Monde':                 'lemonde.fr',
  'Der Spiegel':              'spiegel.de',
  'El País':                  'elpais.com',
  'Irish Times':              'irishtimes.com',
  'RTÉ News':                 'rte.ie',
  'Haaretz':                  'haaretz.com',
  'The Jerusalem Post':       'jpost.com',
  'Arab News':                'arabnews.com',
  'The Japan Times':          'japantimes.co.jp',
  'NHK World':                'nhk.or.jp',
  'Nikkei Asia':              'asia.nikkei.com',
  'The Straits Times':        'straitstimes.com',
  'Sydney Morning Herald':    'smh.com.au',
  'Kyiv Independent':         'kyivindependent.com',
  'The Moscow Times':         'themoscowtimes.com',
  'The Globe and Mail':       'theglobeandmail.com',
  'CNBC':                     'cnbc.com',
  // New general outlets
  'Channel NewsAsia':         'channelnewsasia.com',
  'Hindustan Times':          'hindustantimes.com',
  'The Age':                  'theage.com.au',
  'The Conversation':         'theconversation.com',
  'Washington Examiner':      'washingtonexaminer.com',
  // US political
  'The Intercept':            'theintercept.com',
  'Mother Jones':             'motherjones.com',
  'The Federalist':           'thefederalist.com',
  // Canada
  'National Post':            'nationalpost.com',
  'Toronto Star':             'thestar.com',
  // Science
  'New Scientist':            'newscientist.com',
  'Quanta Magazine':          'quantamagazine.org',
  // Tech outlets
  'The Verge':                'theverge.com',
  'Wired':                    'wired.com',
  'Ars Technica':             'arstechnica.com',
  'TechCrunch':               'techcrunch.com',
  'MIT Technology Review':    'technologyreview.com',
  // Africa & LATAM
  'Mail & Guardian':          'mg.co.za',
  'Africa News':              'africanews.com',
  'Buenos Aires Times':       'batimes.com.ar',
  'Daily Maverick':           'dailymaverick.co.za',
  'Premium Times':            'premiumtimesng.com',
  'The East African':         'theeastafrican.co.ke',
  'African Arguments':        'africanarguments.org',
  'MercoPress':               'mercopress.com',
  'InSight Crime':            'insightcrime.org',
  'Colombia Reports':         'colombiareports.com',
  // Middle East
  'The National':             'thenationalnews.com',
  // US metro dailies
  'Los Angeles Times':        'latimes.com',
  'Chicago Tribune':          'chicagotribune.com',
  'Miami Herald':             'miamiherald.com',
  // Tech & Society
  'Rest of World':            'restofworld.org',
  // Sports outlets
  'BBC Sport':                'bbc.co.uk',
  'Sky Sports':               'skysports.com',
  'ESPN':                     'espn.com',
  'Marca':                    'marca.com',
  'Sports Illustrated':       'si.com',
  // Auto-generated from outlet rss_url hostnames — July 2026 expansion
  'CBS Sports':                'cbssports.com',
  'Autosport':                 'autosport.com',
  'BBC Sport Cricket':         'bbc.co.uk',
  'The Scotsman':              'scotsman.com',
  'The Herald':                'heraldscotland.com',
  'Belfast Telegraph':         'belfasttelegraph.co.uk',
  'This is Money':             'thisismoney.co.uk',
  'The Critic':                'thecritic.co.uk',
  'ConservativeHome':          'conservativehome.com',
  'Novara Media':              'novaramedia.com',
  'Manchester Evening News':   'manchestereveningnews.co.uk',
  'Birmingham Live':           'birminghammail.co.uk',
  'Yorkshire Post':            'yorkshirepost.co.uk',
  'PBS NewsHour':              'pbs.org',
  'Jacobin':                   'jacobin.com',
  'Vanity Fair':               'vanityfair.com',
  'Reason':                    'reason.com',
  'The Washington Times':      'washingtontimes.com',
  'RealClearPolitics':         'realclearpolitics.com',
  'Fast Company':              'fastcompany.com',
  'Vice':                      'vice.com',
  'Gizmodo':                   'gizmodo.com',
  'CNET':                      'cnet.com',
  'Variety':                   'variety.com',
  'Deadline':                  'deadline.com',
  'Chicago Sun-Times':         'chicago.suntimes.com',
  'Yahoo Sports':              'sports.yahoo.com',
  'ESPN Cricinfo':             'espncricinfo.com',
  'BBC Sport Formula 1':       'bbc.co.uk',
  'Daily Record':              'dailyrecord.co.uk',
  'Daily Star':                'dailystar.co.uk',
  'City AM':                   'cityam.com',
  'UnHerd':                    'unherd.com',
  'Byline Times':              'bylinetimes.com',
  'LabourList':                'labourlist.org',
  'indy100':                   'indy100.com',
  'Liverpool Echo':            'liverpoolecho.co.uk',
  'Chronicle Live':            'chroniclelive.co.uk',
  'Wales Online':              'walesonline.co.uk',
  'The New Republic':          'newrepublic.com',
  'Salon':                     'salon.com',
  'Rolling Stone':             'rollingstone.com',
  'The American Conservative': 'theamericanconservative.com',
  'The Daily Caller':          'dailycaller.com',
  'Fortune':                   'fortune.com',
  'Quartz':                    'qz.com',
  'Engadget':                  'engadget.com',
  'Mashable':                  'mashable.com',
  '9to5Mac':                   '9to5mac.com',
  'The Hollywood Reporter':    'hollywoodreporter.com',
  'The Seattle Times':         'seattletimes.com',
  'Las Vegas Review-Journal':  'reviewjournal.com',
  'Meduza':                    'meduza.io',
  'SB Nation':                 'sbnation.com',
  'Guardian Sport':            'theguardian.com',
  'Sky Sports Football':       'skysports.com',
  'The Sporting News':         'sportingnews.com',
  'Independent Sport':         'independent.co.uk',
  'NZ Herald':                 'nzherald.co.nz',
  'Taipei Times':              'taipeitimes.com',
  'Politico Europe':           'politico.eu',
  'Motorsport.com':            'motorsport.com',
  'BBC Sport Football':        'bbc.co.uk',
  'The New Arab':              'newarab.com',
  'Vanguard':                  'vanguardngr.com',
  'Agencia Brasil':            'agenciabrasil.ebc.com.br',
  'Global Voices':             'globalvoices.org',
  'VnExpress International':   'vnexpress.net',
  'Philippine Daily Inquirer': 'newsinfo.inquirer.net',
  'Stuff':                     'stuff.co.nz',
  'Malay Mail':                'malaymail.com',
  'Daily Sabah':               'dailysabah.com',
  'Kyiv Post':                 'kyivpost.com',
  'Egypt Independent':         'egyptindependent.com',
  'MyJoyOnline':               'myjoyonline.com',
  'The Korea Herald':          'koreaherald.com',
  'RNZ':                       'rnz.co.nz',
  'The Daily Star':            'thedailystar.net',
  'ANSA English':              'ansa.it',
  'Bangkok Post':              'bangkokpost.com',
  'Rappler':                   'rappler.com',
  'NL Times':                  'nltimes.nl',
  'Irish Independent':         'independent.ie',
  'Daily News Egypt':          'dailynewsegypt.com',
  'The Herald Zimbabwe':       'herald.co.zw',
  'NDTV':                      'ndtv.com',
  'The Mainichi':              'mainichi.jp',
  'Notes from Poland':         'notesfrompoland.com',
  'The Times of Israel':       'timesofisrael.com',
  'The Standard':              'standardmedia.co.ke',
  'Global News':               'globalnews.ca',
  'Jamaica Gleaner':           'jamaica-gleaner.com',
  'Balkan Insight':            'balkaninsight.com',
  'Al Arabiya English':        'alarabiya.net',
  'Mexico News Daily':         'mexiconewsdaily.com',
  'UN News':                   'news.un.org',
  'The Rio Times':             'riotimesonline.com',
  'Punch':                     'punchng.com',
  // Gap-analysis expansion — July 2026
  'The Register':              'theregister.com',
  'The Local Italy':           'thelocal.it',
  'The Dispatch':              'thedispatch.com',
  'Computer Weekly':           'computerweekly.com',
  'Emerging Europe':           'emerging-europe.com',
  'The Free Press':            'thefp.com',
  'PinkNews':                  'thepinknews.com',
  'Semafor':                   'semafor.com',
  'The 19th':                  '19thnews.org',
  'Morning Star':              'morningstaronline.co.uk',
  'The Bulwark':               'thebulwark.com',
  'The Texas Tribune':         'texastribune.org',
  'The Canary':                'thecanary.co',
  'The Markup':                'themarkup.org',
  'Nation Cymru':              'nation.cymru',
  'STAT News':                 'statnews.com',
  'Glasgow Evening Times':     'eveningtimes.co.uk',
  'Grist':                     'grist.org',
  'TheJournal.ie':             'thejournal.ie',
  'Military Times':            'militarytimes.com',
  'The Portugal News':         'theportugalnews.com',
  'The Oregonian':             'oregonlive.com',
  'Dutch News':                'dutchnews.nl',
  'Minnesota Star Tribune':    'startribune.com',
  'The Local France':          'thelocal.fr',
  'The Local Germany':         'thelocal.de',
  // July 2026 global round 2
  'Al-Monitor':                'al-monitor.com',
  'AllAfrica':                 'allafrica.com',
  'The Diplomat':              'thediplomat.com',
  'Havana Times':              'havanatimes.org',
  'Euractiv':                  'euractiv.com',
  'The Local Spain':           'thelocal.es',
  'Swissinfo':                 'swissinfo.ch',
  'Romania Insider':           'romania-insider.com',
  // July 2026 section-feed expansion
  'BBC World':                'bbc.co.uk',
  'BBC Politics':             'bbc.co.uk',
  'BBC Business':             'bbc.co.uk',
  'BBC Technology':           'bbc.co.uk',
  'BBC Science':              'bbc.co.uk',
  'BBC Health':               'bbc.co.uk',
  'BBC Entertainment':        'bbc.co.uk',
  'Guardian World':           'theguardian.com',
  'Guardian Politics':        'theguardian.com',
  'Guardian Business':        'theguardian.com',
  'Guardian Tech':            'theguardian.com',
  'Guardian Environment':     'theguardian.com',
  'Guardian Science':         'theguardian.com',
  'Guardian Culture':         'theguardian.com',
  'Guardian US':              'theguardian.com',
  'Guardian Australia':       'theguardian.com',
  'Indian Express':           'indianexpress.com',
  'SBS News':                 'sbs.com.au',
  'Yahoo News':               'yahoo.com',
  'Philadelphia Inquirer':    'inquirer.com',
  'UPI':                      'upi.com',
  'The Nation':               'thenation.com',
  'Democracy Now':            'democracynow.org',
  'Washington Free Beacon':   'freebeacon.com',
  'The Local Sweden':         'thelocal.se',
  'The National Scotland':    'thenational.scot',
  'Nature':                   'nature.com',
  'Irish News':               'irishnews.com',
  'NYT World':                'nytimes.com',
  'NYT Politics':             'nytimes.com',
  'NYT Business':             'nytimes.com',
  'NYT Technology':           'nytimes.com',
  'NYT Science':              'nytimes.com',
  'NYT Health':               'nytimes.com',
  'NYT Arts':                 'nytimes.com',
  'Sky News World':           'news.sky.com',
  'Sky News Business':        'news.sky.com',
  'Sky News Politics':        'news.sky.com',
  'Sky News Tech':            'news.sky.com',
  'Independent World':        'independent.co.uk',
  'Independent Business':     'independent.co.uk',
  'Independent Tech':         'independent.co.uk',
  'NPR World':                'npr.org',
  'NPR Politics':             'npr.org',
  'Fox News World':           'foxnews.com',
  'Fox News Politics':        'foxnews.com',
  'AP News':                  'apnews.com',
  'Le Monde English':         'lemonde.fr',
  'El País English':          'elpais.com',
}

// Direct logo URLs for outlets that share a domain with another outlet
// or need a specific branded image instead of the generic favicon
const LOGO_OVERRIDES = {
  'BBC Sport': '/bbc-sport-logo.svg',
}

// Force specific container backgrounds for logos that need it (e.g. light/yellow SVGs on light bg)
const CONTAINER_BG_OVERRIDES = {
  'BBC Sport': { background: '#0f1923', border: 'none' },
}

export default function OutletLogo({ name = '', size = 32, borderRadius = 8, style = {} }) {
  const [failed, setFailed] = useState(false)
  const override = LOGO_OVERRIDES[name]
  const domain = OUTLET_DOMAINS[name]
  const [bg, fg] = outletColor(name)

  const base = {
    width: size,
    height: size,
    borderRadius,
    flexShrink: 0,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...style,
  }

  const logoSrc = override || (domain ? `https://www.google.com/s2/favicons?domain=${domain}&sz=64` : null)
  const containerOverride = CONTAINER_BG_OVERRIDES[name] || {}

  if (logoSrc && !failed) {
    return (
      <div style={{ ...base, background: bg, ...containerOverride }}>
        <img
          src={logoSrc}
          alt={name}
          onError={() => setFailed(true)}
          style={{ width: size * 0.65, height: size * 0.65, objectFit: 'contain' }}
        />
      </div>
    )
  }

  // Fallback: coloured initials
  return (
    <div style={{ ...base, background: bg, color: fg, fontSize: size * 0.3, fontWeight: 500 }}>
      {outletInitials(name || '?')}
    </div>
  )
}
