import React from 'react'
import { scoreColor } from '../utils/helpers'
import OutletLogo from './OutletLogo'
import InfoTip from './InfoTip'

export default function Sidebar({ outlets, navigate }) {
  const top5 = outlets.filter(o => (o.overall_score || 0) > 0 && !o.parent_outlet_id).sort((a, b) => (b.overall_score || 0) - (a.overall_score || 0)).slice(0, 5)

  return (
    <div className="sidebar">
      <div className="widget">
        <div className="widget-title">Top rated outlets</div>
        {top5.length === 0
          ? <div className="skeleton" style={{ height: 200 }}></div>
          : top5.map((o, i) => {
              const score = o.overall_score || 0
              return (
                <div key={o.id} className="outlet-rank-row" onClick={() => navigate('outlet', { outletId: o.id })}>
                  <span className="rank-num">{i + 1}</span>
                  <OutletLogo name={o.name} size={30} borderRadius={7} />
                  <span className="outlet-rank-name">{o.name}</span>
                  <div className="outlet-rank-bar-wrap">
                    <div className="rank-bar-bg">
                      <div className="rank-bar-fill" style={{ width: `${score}%`, background: scoreColor(score) }}></div>
                    </div>
                    <div className="rank-val" style={{ color: scoreColor(score) }}>{score}</div>
                  </div>
                </div>
              )
            })
        }
        <button
          className="btn-outline"
          style={{ width: '100%', marginTop: 12, fontSize: 12 }}
          onClick={() => navigate('outlets')}
        >
          Full rankings →
        </button>
      </div>
      <div className="widget">
        <div className="widget-title">How scores are built</div>
        <div style={{ fontSize: 12, color: 'var(--text2)', lineHeight: 1.6, marginBottom: 12 }}>
          Every article is scored by Claude AI for quality, political bias, and headline fairness. Outlet scores blend AI analysis with reader ratings once 20+ community votes are recorded.
        </div>
        <div className="rating-breakdown">
          <div className="rb-row">
            <span className="rb-label">AI analysis</span>
            <div className="rb-bar-bg"><div className="rb-bar-fill" style={{ width: '80%', background: 'var(--blue)' }}></div></div>
            <span className="rb-val" style={{ color: 'var(--blue)' }}>80%</span>
            <InfoTip text="Scores are generated by Claude AI from each article's headline and summary. Outlet scores reflect patterns across the last 30 days — not individual verdicts." />
          </div>
          <div className="rb-row">
            <span className="rb-label">Community</span>
            <div className="rb-bar-bg"><div className="rb-bar-fill" style={{ width: '20%', background: 'var(--amber)' }}></div></div>
            <span className="rb-val" style={{ color: 'var(--amber)' }}>20%</span>
            <InfoTip text="Reader star ratings are blended in at 20% once an outlet has 20 or more community ratings. Below that threshold, the score is 100% AI." />
          </div>
        </div>
        <a
          href="/methodology"
          style={{ display: 'block', marginTop: 12, fontSize: 11, color: 'var(--text3)', textDecoration: 'none', textAlign: 'right' }}
        >
          Full methodology →
        </a>
      </div>
    </div>
  )
}
